# Generated by Django 3.1.2 on 2020-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mahasiswa', models.CharField(max_length=100)),
                ('nim_mahasiswa', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hewan',
        ),
    ]
